using System;

namespace Serializer.Abstractions
{
    /// <summary>
    /// Marks a type as binary serializable. Types with this attribute will have
    /// serialization code generated by the Serializer.Generator project.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    public sealed class BinarySerializableAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BinarySerializableAttribute"/> class.
        /// </summary>
        public BinarySerializableAttribute()
        {
        }
    }
}
